
export const LOAD_DATA = 'LOAD_DATA'
export const ERROR_MSG = 'ERROR_MSG'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'


export const GETBOSSGENIUSLIST = 'GETBOSSGENIUSLIST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'